export const db = {
  intents: new Map(),
  merchantRules: new Map(),
  offers: new Map(),
  offerEvents: [],
  redemptions: new Map(),
  cashbackByUser: new Map(),
  context: {
    weather: [],
    events: [],
    payone: [],
  },
  merchants: [
    {
      merchant_id: "m_1021",
      name: "Cafe Muller",
      category: "cafe",
      area_cell_id: "u0wtm3",
      lat: 48.7758,
      lon: 9.1829,
      is_open_now: true,
      price_band: "mid",
      avg_ticket_size_eur: 8.5,
    },
    {
      merchant_id: "m_2042",
      name: "Books & Brews",
      category: "bookstore",
      area_cell_id: "u0wtm6",
      lat: 48.7823,
      lon: 9.177,
      is_open_now: true,
      price_band: "mid",
      avg_ticket_size_eur: 12,
    },
  ],
};
